export const BRAND_COLORS = {
  primary: '#4F39F6', // Vivid indigo/purple
  primaryHover: '#4331D4',
  primaryLight: '#EEECFF',
  darkNavy: '#0F172B', // Deep navy status/nav
  darkSecondary: '#1A263A',
  bgLight: '#F5F7FA',
  bgDark: '#0B1120',
  cardLight: '#FFFFFF',
  cardDark: '#131C2E',
  textPrimaryLight: '#0F172A',
  textSecondaryLight: '#64748B',
  textPrimaryDark: '#F8FAFC',
  textSecondaryDark: '#94A3B8',
  borderLight: '#E2E8F0',
  borderDark: '#1E293B',
  success: '#10B981',
  successLight: '#E6F4EA',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  error: '#F43F5E',
  errorLight: '#FFE4E6',
  info: '#3B82F6',
  infoLight: '#EFF6FF',
};

export const FLUTTER_WIDGET_MAPPINGS: Record<string, string> = {
  home: 'HomeScreen (StatelessWidget + ConsumerWidget)',
  attendance: 'AttendanceScreen (StatefulWidget with Timer)',
  leave: 'LeaveDashboardScreen & ApplyLeaveForm',
  manager_leave_approvals: 'ManagerLeaveApprovalsScreen (SliverList)',
  my_team: 'TeamListScreen & TeamMemberDetailSheet',
  team_attendance: 'TeamAttendanceScreen (ListView.builder)',
  team_performance: 'TeamPerformanceScreen (Charts + GridView)',
  payslips: 'PayslipsListScreen & PayslipDetailPdfModal',
  performance: 'PerformanceGoalsScreen & ReviewCard',
  helpdesk: 'HelpdeskTicketsScreen & ChatThreadView',
  calendar: 'MasterCalendarScreen (TableCalendar)',
  requests: 'SelfServiceRequestsScreen & RequestFormSheet',
  announcements: 'AnnouncementsScreen (ExpansionTile List)',
  documents: 'DocumentsCenterScreen & PdfViewerModal',
  notifications: 'NotificationsCenterScreen (Dismissible ListView)',
  profile: 'EmployeeProfileScreen (TabBar + CustomScrollView)',
  settings: 'AppSettingsScreen (SwitchListTile ListView)',
  more: 'MoreMenuSheet (GridView.count)',
};
