import {
  User,
  AttendanceRecord,
  LeaveBalance,
  LeaveRequest,
  Payslip,
  Goal,
  PerformanceReview,
  HelpdeskTicket,
  Announcement,
  CalendarEvent,
  SelfServiceRequest,
  EmployeeDocument,
  AppNotification,
  TeamMember,
} from './types';

export const EMPLOYEE_USER: User = {
  id: 'emp-001',
  name: 'Alex Morgan',
  email: 'alex.morgan@company.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  designation: 'Senior UI/UX Designer',
  department: 'Product & Design',
  employeeId: 'EMP-4089',
  role: 'EMPLOYEE',
  joiningDate: '15 Jan 2023',
  employmentType: 'Full-Time',
  managerName: 'Sarah Jenkins',
  phone: '+1 (555) 234-5678',
  dob: '12 May 1994',
  address: '452 Pine Street, San Francisco, CA 94103',
  emergencyContact: {
    name: 'David Morgan',
    relationship: 'Spouse',
    phone: '+1 (555) 987-6543',
  },
};

export const MANAGER_USER: User = {
  id: 'mgr-001',
  name: 'Sarah Jenkins',
  email: 'sarah.jenkins@company.com',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  designation: 'Lead Engineering Manager',
  department: 'Product & Design',
  employeeId: 'MGR-1024',
  role: 'MANAGER',
  joiningDate: '10 Aug 2021',
  employmentType: 'Full-Time',
  managerName: 'Robert Sterling (VP Eng)',
  phone: '+1 (555) 345-6789',
  dob: '24 Oct 1988',
  address: '88 Market St, San Francisco, CA 94105',
  emergencyContact: {
    name: 'Mark Jenkins',
    relationship: 'Spouse',
    phone: '+1 (555) 765-4321',
  },
};

export const MOCK_LEAVE_BALANCES: LeaveBalance[] = [
  { type: 'Paid Leave', total: 18, used: 6, remaining: 12, color: '#4F39F6' },
  { type: 'Casual Leave', total: 10, used: 3, remaining: 7, color: '#3B82F6' },
  { type: 'Sick Leave', total: 12, used: 2, remaining: 10, color: '#10B981' },
  { type: 'Maternity/Paternity', total: 90, used: 0, remaining: 90, color: '#F59E0B' },
];

export const MOCK_ATTENDANCE_HISTORY: AttendanceRecord[] = [
  {
    id: 'att-101',
    date: '2026-08-12',
    status: 'Present',
    clockIn: '08:58 AM',
    clockOut: '05:30 PM',
    totalHours: '8h 32m',
    breakDuration: '45m',
    notes: 'On time. Working on mobile app UI specs.',
  },
  {
    id: 'att-100',
    date: '2026-08-11',
    status: 'Present',
    clockIn: '09:02 AM',
    clockOut: '06:05 PM',
    totalHours: '9h 03m',
    breakDuration: '50m',
  },
  {
    id: 'att-099',
    date: '2026-08-10',
    status: 'Late',
    clockIn: '09:35 AM',
    clockOut: '06:15 PM',
    totalHours: '8h 40m',
    breakDuration: '40m',
    notes: 'Traffic delay on Bay Bridge',
  },
  {
    id: 'att-098',
    date: '2026-08-07',
    status: 'Present',
    clockIn: '08:52 AM',
    clockOut: '05:45 PM',
    totalHours: '8h 53m',
    breakDuration: '45m',
  },
  {
    id: 'att-097',
    date: '2026-08-06',
    status: 'On Leave',
    notes: 'Approved Casual Leave',
  },
  {
    id: 'att-096',
    date: '2026-08-05',
    status: 'Half Day',
    clockIn: '09:00 AM',
    clockOut: '01:30 PM',
    totalHours: '4h 30m',
    notes: 'Doctor appointment in afternoon',
  },
  {
    id: 'att-095',
    date: '2026-08-04',
    status: 'Present',
    clockIn: '08:55 AM',
    clockOut: '05:30 PM',
    totalHours: '8h 35m',
  },
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lv-201',
    employeeId: 'emp-001',
    employeeName: 'Alex Morgan',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    leaveType: 'Paid Leave',
    startDate: '2026-08-25',
    endDate: '2026-08-28',
    totalDays: 4,
    reason: 'Annual family vacation trip to Lake Tahoe.',
    status: 'Pending',
    appliedDate: '10 Aug 2026',
  },
  {
    id: 'lv-202',
    employeeId: 'emp-001',
    employeeName: 'Alex Morgan',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    leaveType: 'Sick Leave',
    startDate: '2026-07-14',
    endDate: '2026-07-14',
    totalDays: 1,
    reason: 'Dental surgery and post-op recovery.',
    attachmentName: 'dental_doctor_note.pdf',
    status: 'Approved',
    appliedDate: '13 Jul 2026',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: '13 Jul 2026',
  },
  {
    id: 'lv-203',
    employeeId: 'emp-002',
    employeeName: 'Marcus Vance',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    leaveType: 'Casual Leave',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    totalDays: 2,
    reason: 'Personal urgent errand at DMV and bank.',
    status: 'Pending',
    appliedDate: '11 Aug 2026',
  },
  {
    id: 'lv-204',
    employeeId: 'emp-003',
    employeeName: 'Elena Rostova',
    employeeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    leaveType: 'Paid Leave',
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    totalDays: 2,
    reason: 'Attending Figma Config Design Summit.',
    status: 'Pending',
    appliedDate: '09 Aug 2026',
  },
  {
    id: 'lv-205',
    employeeId: 'emp-004',
    employeeName: 'David Chen',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    leaveType: 'Sick Leave',
    startDate: '2026-08-03',
    endDate: '2026-08-04',
    totalDays: 2,
    reason: 'Flu symptoms and fever.',
    status: 'Approved',
    appliedDate: '03 Aug 2026',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: '03 Aug 2026',
  },
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-801',
    month: 'July',
    year: 2026,
    netSalary: 7420,
    grossSalary: 8800,
    totalDeductions: 1380,
    status: 'Paid',
    issueDate: '31 Jul 2026',
    earnings: {
      basic: 4800,
      hra: 2000,
      transport: 800,
      specialAllowance: 1200,
    },
    deductions: {
      pf: 520,
      tax: 680,
      insurance: 180,
    },
  },
  {
    id: 'ps-800',
    month: 'June',
    year: 2026,
    netSalary: 7420,
    grossSalary: 8800,
    totalDeductions: 1380,
    status: 'Paid',
    issueDate: '30 Jun 2026',
    earnings: {
      basic: 4800,
      hra: 2000,
      transport: 800,
      specialAllowance: 1200,
    },
    deductions: {
      pf: 520,
      tax: 680,
      insurance: 180,
    },
  },
  {
    id: 'ps-799',
    month: 'May',
    year: 2026,
    netSalary: 7420,
    grossSalary: 8800,
    totalDeductions: 1380,
    status: 'Paid',
    issueDate: '31 May 2026',
    earnings: {
      basic: 4800,
      hra: 2000,
      transport: 800,
      specialAllowance: 1200,
    },
    deductions: {
      pf: 520,
      tax: 680,
      insurance: 180,
    },
  },
];

export const MOCK_GOALS: Goal[] = [
  {
    id: 'gl-001',
    title: 'Mobile App Flutter UI System',
    description: 'Design and prototype full Flutter mobile application specs for HRMS.',
    kpi: 'Complete 25+ pixel-perfect screen designs',
    target: '25 Screens',
    currentValue: '21 Screens',
    progressPercent: 84,
    deadline: '20 Aug 2026',
    status: 'On Track',
    managerComments: 'Great progress on Flutter widget structural components.',
  },
  {
    id: 'gl-002',
    title: 'Design System Token Accessibility',
    description: 'Ensure WCAG AA compliance across primary indigo palette and high-contrast dark theme.',
    kpi: '100% WCAG AA test pass',
    target: '4.5:1 Ratio',
    currentValue: '4.8:1 Ratio',
    progressPercent: 100,
    deadline: '10 Aug 2026',
    status: 'Completed',
    managerComments: 'Verified and approved on August 10.',
  },
  {
    id: 'gl-003',
    title: 'User Micro-Interactions & Transitions',
    description: 'Craft fluid motion states for clock-in live timers and leave submission sheets.',
    kpi: 'Sub-100ms response feel',
    target: '60 FPS',
    currentValue: '52 FPS',
    progressPercent: 65,
    deadline: '30 Aug 2026',
    status: 'At Risk',
    managerComments: 'Needs optimization on low-end test Android devices.',
  },
];

export const MOCK_PERFORMANCE_REVIEWS: PerformanceReview[] = [
  {
    id: 'pr-10',
    period: 'H1 2026 Performance Review',
    overallRating: 4.8,
    status: 'Completed',
    strengths: [
      'Exceptional mobile-first UI architecture skills',
      'Proactive team communication and cross-functional support',
      'Meticulous adherence to design token consistency',
    ],
    areasForImprovement: [
      'Expand user testing with remote field staff',
      'Document design tokens in Flutter Storybook',
    ],
    managerFeedback:
      'Alex has delivered stellar design output for our HR product suite. Her attention to mobile usability and clean navigation design sets a benchmark across the engineering org.',
    employeeComments:
      'Thank you for the guidance! I look forward to pushing our Flutter UI component library even further in H2.',
    reviewDate: '15 Jul 2026',
  },
];

export const MOCK_HELPDESK_TICKETS: HelpdeskTicket[] = [
  {
    id: 'tk-501',
    ticketNumber: 'TKT-8902',
    subject: 'Request for secondary monitor for remote workstation',
    category: 'IT Support',
    priority: 'Medium',
    status: 'In Progress',
    createdAt: '08 Aug 2026',
    description: 'Need a 27-inch 4K color-calibrated display for design work.',
    messages: [
      {
        id: 'msg-1',
        senderName: 'Alex Morgan',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        isStaff: false,
        text: 'Hi IT team, I submitted a request for a secondary monitor approval.',
        timestamp: '08 Aug, 10:15 AM',
      },
      {
        id: 'msg-2',
        senderName: 'Jason (IT Helpdesk)',
        senderAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        isStaff: true,
        text: 'Hello Alex! Your request was approved by Sarah. Order placed with Dell Logistics, tracking info will follow.',
        timestamp: '09 Aug, 02:30 PM',
      },
    ],
  },
  {
    id: 'tk-502',
    ticketNumber: 'TKT-8840',
    subject: 'Question regarding W-2 Tax form revision',
    category: 'Payroll',
    priority: 'Low',
    status: 'Resolved',
    createdAt: '28 Jul 2026',
    description: 'Clarification on state tax withholding adjustment.',
    messages: [
      {
        id: 'msg-1',
        senderName: 'Alex Morgan',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        isStaff: false,
        text: 'Can I update my state tax allowance online?',
        timestamp: '28 Jul, 11:00 AM',
      },
      {
        id: 'msg-2',
        senderName: 'Payroll HR Support',
        senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        isStaff: true,
        text: 'Yes! Go to Self-Service Requests -> Bank/Tax Detail Change to upload W-4 directly.',
        timestamp: '28 Jul, 04:15 PM',
      },
    ],
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Company All-Hands Meeting & Q3 Product Roadmap',
    summary: 'Join us this Thursday at 10 AM PST for strategic updates and product showcase.',
    content:
      'We are excited to host our quarterly All-Hands session! Agenda includes Q3 financial updates, unveiling the new PulseHR Flutter mobile app, and employee spotlight awards. Coffee and snacks provided at SF HQ.',
    publishedDate: '11 Aug 2026',
    category: 'Company',
    priority: 'High',
    isRead: false,
    author: 'HR Operations',
  },
  {
    id: 'ann-2',
    title: 'Updated Parental Leave & Wellness Reimbursement Policy',
    summary: 'New benefits effective September 1st including $1,000 annual gym & mental health credit.',
    content:
      'Starting Sept 1, 2026, parental leave increases to 16 weeks paid for primary caregivers. Furthermore, every employee receives a $1,000 annual flexible wellness credit applicable to gym memberships, yoga, or therapy.',
    publishedDate: '05 Aug 2026',
    category: 'Policy',
    priority: 'Normal',
    isRead: true,
    author: 'People & Culture',
  },
  {
    id: 'ann-3',
    title: 'Office Security Patch & Mobile Keycard Update',
    summary: 'SF Office doors will migrate to Bluetooth digital badges via mobile app.',
    content:
      'In preparation for smart office upgrades, please ensure your mobile app notifications and Bluetooth permissions are enabled for seamless badge entry starting next Monday.',
    publishedDate: '01 Aug 2026',
    category: 'HR Notice',
    priority: 'Normal',
    isRead: true,
    author: 'Facilities Management',
  },
];

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'ev-1',
    title: 'Labor Day Public Holiday',
    date: '2026-09-07',
    type: 'Holiday',
    description: 'National holiday - All office locations closed.',
    color: '#F43F5E',
  },
  {
    id: 'ev-2',
    title: 'Alex Lake Tahoe Leave',
    date: '2026-08-25',
    type: 'Leave',
    description: 'Approved Paid Leave',
    color: '#4F39F6',
  },
  {
    id: 'ev-3',
    title: 'Q3 All-Hands Meeting',
    date: '2026-08-13',
    type: 'Company Event',
    description: 'Main auditorium & Zoom livestream at 10:00 AM.',
    color: '#10B981',
  },
  {
    id: 'ev-4',
    title: 'H2 Performance Review Self-Evaluation Deadline',
    date: '2026-08-31',
    type: 'Deadline',
    description: 'Submit goal self-ratings before midnight.',
    color: '#F59E0B',
  },
];

export const MOCK_SELF_SERVICE_REQUESTS: SelfServiceRequest[] = [
  {
    id: 'req-301',
    requestType: 'Employment Certificate',
    appliedDate: '09 Aug 2026',
    description: 'Requested stamped employment confirmation letter for apartment lease application.',
    status: 'Completed',
    comments: 'Certificate generated and attached in Documents.',
    attachmentName: 'Employment_Certificate_AlexMorgan.pdf',
  },
  {
    id: 'req-302',
    requestType: 'Attendance Correction',
    appliedDate: '10 Aug 2026',
    description: 'Clocked out late due to emergency client release; clock-out timestamp 06:15 PM instead of 05:30 PM.',
    status: 'Pending',
  },
  {
    id: 'req-303',
    requestType: 'Profile Update',
    appliedDate: '01 Jul 2026',
    description: 'Update home address to 452 Pine Street, San Francisco.',
    status: 'Approved',
    comments: 'Verified with utility bill submission.',
  },
];

export const MOCK_DOCUMENTS: EmployeeDocument[] = [
  {
    id: 'doc-01',
    name: 'Offer Letter & Employment Agreement',
    category: 'My Documents',
    dateAdded: '15 Jan 2023',
    fileType: 'PDF',
    fileSize: '1.4 MB',
  },
  {
    id: 'doc-02',
    name: 'W-4 Tax Withholding Allowance Form 2026',
    category: 'Certificates',
    dateAdded: '02 Jan 2026',
    fileType: 'PDF',
    fileSize: '420 KB',
  },
  {
    id: 'doc-03',
    name: 'Employee Handbook & Code of Conduct v4',
    category: 'Company Policies',
    dateAdded: '10 Mar 2026',
    fileType: 'PDF',
    fileSize: '3.8 MB',
  },
  {
    id: 'doc-04',
    name: 'Payslip - July 2026',
    category: 'Payslips',
    dateAdded: '31 Jul 2026',
    fileType: 'PDF',
    fileSize: '180 KB',
  },
  {
    id: 'doc-05',
    name: 'Verified Employment Certificate',
    category: 'My Documents',
    dateAdded: '09 Aug 2026',
    fileType: 'PDF',
    fileSize: '310 KB',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Leave Request Received',
    description: 'Your leave request for Aug 25 - Aug 28 is currently under review by Sarah Jenkins.',
    timestamp: '10 Aug, 11:20 AM',
    category: 'Leave',
    isRead: false,
    targetScreen: 'leave',
  },
  {
    id: 'notif-2',
    title: 'July Payslip Published',
    description: 'Your net salary of $7,420.00 has been direct deposited.',
    timestamp: '31 Jul, 09:00 AM',
    category: 'Payroll',
    isRead: true,
    targetScreen: 'payslips',
  },
  {
    id: 'notif-3',
    title: 'New Company Announcement',
    description: 'Q3 All-Hands Meeting & Roadmap update released.',
    timestamp: '11 Aug, 08:30 AM',
    category: 'Announcements',
    isRead: false,
    targetScreen: 'announcements',
  },
  {
    id: 'notif-4',
    title: 'Helpdesk Ticket Update',
    description: 'Jason replied to TKT-8902 regarding monitor delivery.',
    timestamp: '09 Aug, 02:30 PM',
    category: 'Helpdesk',
    isRead: true,
    targetScreen: 'helpdesk',
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Alex Morgan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    designation: 'Senior UI/UX Designer',
    department: 'Product & Design',
    joiningDate: '15 Jan 2023',
    email: 'alex.morgan@company.com',
    phone: '+1 (555) 234-5678',
    statusToday: 'Present',
    clockInTime: '08:58 AM',
    workingHoursToday: '3h 45m',
    pendingLeavesCount: 1,
    goalCompletionRate: 84,
    rating: 4.8,
  },
  {
    id: 'tm-2',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    designation: 'Staff Product Designer',
    department: 'Product & Design',
    joiningDate: '01 Mar 2022',
    email: 'marcus.vance@company.com',
    phone: '+1 (555) 345-9876',
    statusToday: 'Work From Home',
    clockInTime: '09:05 AM',
    workingHoursToday: '3h 38m',
    pendingLeavesCount: 1,
    goalCompletionRate: 92,
    rating: 4.9,
  },
  {
    id: 'tm-3',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    designation: 'UX Researcher',
    department: 'Product & Design',
    joiningDate: '12 Nov 2023',
    email: 'elena.rostova@company.com',
    phone: '+1 (555) 456-7890',
    statusToday: 'Present',
    clockInTime: '08:45 AM',
    workingHoursToday: '3h 58m',
    pendingLeavesCount: 1,
    goalCompletionRate: 78,
    rating: 4.6,
  },
  {
    id: 'tm-4',
    name: 'David Chen',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    designation: 'Design Systems Engineer',
    department: 'Product & Design',
    joiningDate: '05 Jun 2021',
    email: 'david.chen@company.com',
    phone: '+1 (555) 567-8901',
    statusToday: 'On Leave',
    pendingLeavesCount: 0,
    goalCompletionRate: 95,
    rating: 4.9,
  },
  {
    id: 'tm-5',
    name: 'Sophia Patel',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    designation: 'Junior Visual Designer',
    department: 'Product & Design',
    joiningDate: '10 Feb 2024',
    email: 'sophia.patel@company.com',
    phone: '+1 (555) 678-9012',
    statusToday: 'Late',
    clockInTime: '09:40 AM',
    workingHoursToday: '3h 03m',
    pendingLeavesCount: 0,
    goalCompletionRate: 70,
    rating: 4.4,
  },
];
